name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_achievements: yes
          plugin_achievements_only: >-
                polyglot, maintainer, deployer, maintainer, developer,
                scripter, packager, influencer, contributer
          plugin_languages: yes
          plugin_languages_ignored: >-
            dockerfile, cmake
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 10
          plugin_lines: yes
          plugin_lines_delay: 30
          plugin_repositories: yes
          plugin_repositories_featured: kile/killua
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: "76561199183707900"
          plugin_steam_sections: recently-played
          plugin_steam_achievements_limit: 0
          
